resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: flask-app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/rayeno/flask-app:latest
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: prod
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: latest
  - target:
      kind: Ingress
      name: flask-app
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: flask-prod.local

namespace: prod